### ISSUE TITLE
Super pedantic technicality with overflow/underflow terminology in DDC notes

### ISSUE THREAD

**Issue by PickledCow** [Nylilsa/nylilsa.github.io#6]
Extremely pedantic but the DDC "underflow" is technically still an overflow because officially the term overflow does not care about direction while underflow is a floating point number term where a number is too small to represent and is stored as 0.

**Comment by PickledCow** [comment]
Looks like in the footer it also links to the wrong Wikipedia page, linking to the [floating point underflow page](https://en.wikipedia.org/wiki/Arithmetic_underflow) instead of the [integer overflow page](https://en.wikipedia.org/wiki/Integer_overflow).

**Comment by Nylilsa** [comment]
Fixed as of https://github.com/Nylilsa/nylilsa.github.io/commit/230935fb192662d8be17e12007540be0d81fba91.
